### ISSUE TITLE
How to change Deployment Info?

### ISSUE THREAD

**Issue by nshoes** [apache/cordova-node-xcode#57]
Looking to update General -> Deployment Info -> Devices; how can I do this? Are there docs for this project anywhere?

**Comment by brodybits** [comment]
If you don't see documentation I think you can consider it to be undocumented and unsupported behavior. Contribution of documentation with testing would be much appreciated. Contribution to the test suite would be a big extra bonus.

My apologies for lack of response. Maintainers are completely overloaded since we lost support from 2 big companies.

**Comment by crapthings** [comment]
@nshoes 

buildSettingsObj.IPHONEOS_DEPLOYMENT_TARGET = '9.0'
buildSettingsObj.TARGETED_DEVICE_FAMILY = '1,2'

```js
    var configurations = pbxProject.pbxXCBuildConfigurationSection()
    for (var key in configurations) {
      if (typeof configurations[key].buildSettings !== 'undefined') {
        var buildSettingsObj = configurations[key].buildSettings
        if (typeof buildSettingsObj.PRODUCT_NAME !== 'undefined') {
          var productName = buildSettingsObj.PRODUCT_NAME
          if (productName.indexOf('shareextension') >= 0) {
            buildSettingsObj.IPHONEOS_DEPLOYMENT_TARGET = '9.0'
            buildSettingsObj.TARGETED_DEVICE_FAMILY = '1,2'
          }
        }
      }
    }
```
